# Generated by Django 5.2.6 on 2025-09-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(blank=True, choices=[('local', 'Email and Password'), ('google', 'Google Account'), ('apple', 'Apple Account')], default='email', max_length=50),
        ),
    ]
