# Generated by Django 5.2.6 on 2025-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apple_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(blank=True, choices=[('email', 'Email and Password'), ('google', 'Google Account'), ('apple', 'Apple Account')], default='email', max_length=50),
        ),
    ]
